# Generated by Django 3.0.6 on 2020-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Restaurant name')),
                ('foodtype', models.CharField(max_length=200, verbose_name='Food type')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip', models.IntegerField(verbose_name='Zip')),
                ('image', models.ImageField(upload_to='static/images')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
